name: AI Changelog Sync

on:
  workflow_dispatch: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap AI template kit
        run: node ai/scripts/bootstrap.mjs

      - name: Record changelog agent run
        env:
          AI_AGENT_NAME: changelog
        run: node ai/scripts/log-agent-run.mjs

      - name: Upload AI changelog context
        uses: actions/upload-artifact@v4
        with:
          name: ai-changelog-context
          path: |
            ai/_state
            ai/logs
          if-no-files-found: warn
