name: AI README Sync

on:
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap AI template kit
        run: node ai/scripts/bootstrap.mjs

      - name: Record README sync agent run
        env:
          AI_AGENT_NAME: readme-sync
        run: node ai/scripts/log-agent-run.mjs

      - name: Upload README sync context
        uses: actions/upload-artifact@v4
        with:
          name: ai-readme-sync-context
          path: |
            ai/_state
            ai/logs
          if-no-files-found: warn
