name: Harness Nightly
permissions:
  contents: read

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  harness-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Prepare artifact directory
        run: mkdir -p artifacts
      - name: Run harness smoke
        env:
          HARNESS_REPORT_JSON: artifacts/harness-report.json
          HARNESS_REPORT_HTML: artifacts/harness-report.html
        run: npm run ci:harness
      - name: Upload harness artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: harness-report
          path: artifacts
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "Harness Nightly run *${{ github.run_number }}* for `${{ github.ref_name }}` ${JOB_STATUS} | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#15803d' || '#b91c1c' }}",
                  "fields": [
                    { "title": "Status", "value": "${JOB_STATUS}", "short": true },
                    { "title": "Scenario", "value": "orders-transactions", "short": true }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOB_STATUS: ${{ job.status }}
